In [118]:
import numpy as np

The Basics 

In [110]:
a= np.array([1,2,3], dtype='int16')

In [111]:
print(a)

[1 2 3]


In [112]:
b = np.array([[9,0,8,0,7, 0], [6,0,4,0,4,0]])

In [18]:
print(b)

[[9 0 8 0 7 0]
 [6 0 4 0 4 0]]


In [19]:
# getting the dimension

In [20]:
a.ndim

1

In [21]:
b.ndim

2

In [22]:
# get shape

In [23]:
a.shape

(3,)

In [24]:
b.shape

(2, 6)

In [31]:
# how much memory. get the type, you can also specified the type that you want to store this
a.dtype 

dtype('int16')

In [33]:
# get total size
a.size * a.itemsize

6

In [35]:
# get the size
a.size

3

In [36]:
# get size in bytes. Since it is int16, it spits 2 bytes, but if its int32, it will give you 4 bytes
a.itemsize


2

In [37]:
#total size
a.size * a.itemsize

6

In [38]:
# this above is equivalent with
a.nbytes

6

Accessing/Chaning specific elements, rows, columns,etc

In [39]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,13]])

In [41]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 13]]


In [42]:
a.shape

(2, 7)

In [43]:
# get a specific element [r, c]
a[1,5]

13

In [44]:
# using negative notation
a[1, -1]

13

In [45]:
# get a scpecific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [46]:
# geta specific column
a[:, 2]

array([ 3, 10])

In [49]:
# getting a little more fancy [startindex: endindex: stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [50]:
a[1,5] = 20

In [51]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 13]]


In [69]:
a[:,2] = [10,2]

In [70]:
print(a)

[[ 1  2 10  4  5  6  7]
 [ 8  9  2 11 12 20 13]]


In [71]:
a[:,2]= 5

In [72]:
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 13]]


In [73]:
# 3d example

In [77]:
b = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])

In [78]:
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [79]:
# get a specific element - work outside in
b[0,1,1]

4

In [80]:
# replacing
b[:,1,:] = [[9,9], [8,8]]

In [81]:
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [82]:
#initializing different types of arrays
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [83]:
np.zeros((2,3)) # two dimensions 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [84]:
np.zeros((2,3,3,2)) #four dimensions

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [85]:
# all 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [88]:
# any other number
np.full((2,2), 99) # a two by two with value 99

array([[99, 99],
       [99, 99]])

In [92]:
# any other number (full_like). this allows us to take a shape that is already build
np.full_like(a, 4)

array([4, 4])

In [94]:
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [96]:
# random decimal numbers
np.random.rand(4,2)

array([[0.13271037, 0.16617152],
       [0.93071039, 0.64630237],
       [0.64129067, 0.47578918],
       [0.37333163, 0.33882618]])

In [97]:
# to pass in a shape
np.random.random_sample(a.shape)

array([[0.31743858, 0.57136914, 0.4562291 , 0.63189922, 0.62235003,
        0.15041187, 0.33327387],
       [0.82722571, 0.03593508, 0.84669369, 0.83208602, 0.41068669,
        0.65166509, 0.41167936]])

In [98]:
# random integer values
np.random.randint(7, size=(3,3))

array([[3, 1, 3],
       [6, 2, 3],
       [1, 1, 1]])

In [99]:
# random integrer values
np.random.randint(4,8, size=(3,3))

array([[4, 7, 5],
       [6, 6, 5],
       [4, 4, 7]])

In [117]:
np.identity(5)

AttributeError: 'numpy.ndarray' object has no attribute 'identity'

In [127]:
arr = np.array([[1,2,3]])
# r1 = np.repeat(arr,3)

In [129]:
r1 = np.repeat(arr, 3, axis = 1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


[1 1 1 2 2 2 3 3 3]


In [135]:
#excericse
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
print(z)

output[1:4, 1:4] = z 

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [136]:
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### be careful when copying arrays!! in here a and b are poitning at the same object. fix it by creating a copy

In [142]:
a = np.array([1,2,3])
b=a.copy()

In [143]:
print(b)

[1 2 3]


In [144]:
b[0] = 100 


In [145]:
print(b)

[100   2   3]


In [146]:
print(a)

[1 2 3]


# mathematics

In [147]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [148]:
a + 2

array([3, 4, 5, 6])

In [149]:
a -2

array([-1,  0,  1,  2])

In [150]:
a * 2

array([2, 4, 6, 8])

In [151]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [153]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [154]:
a ** 2

array([ 1,  4,  9, 16])

In [155]:
# take the sin of all values
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [156]:
# take the cosine of all the values
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

####linear algebra

In [161]:
a = np.ones((2,3))
print(a)
b = np.full((3,2), 2)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [164]:
# find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [165]:
####statistics with numpy

In [166]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [167]:
np.min(stats)

1

In [170]:
np.max(stats, axis=1)

array([3, 6])

In [171]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [172]:
###reorganizing arrays

In [175]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before.shape)

after = before.reshape((8,1))

(2, 4)


In [176]:
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [177]:
# Vertically stacking vectors 
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [181]:
# Horizontal stacks are pretty similar
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [182]:
#Micellaneous
# load data from file

filedata = np.genfromtxt('data.txt', delimeter=',')


In [184]:
filedata.astype('int32')
filedata = filedate.astype('int32')
filedata

NameError: name 'filedata' is not defined

In [186]:
### boolean masking advance indexing
filedata > 50 
filedata[filedata > 50]
## you can index with a list in numpy
np.array([1,2,3,4,5,6,7])
a[[1,2,8]]



NameError: name 'filedata' is not defined

In [187]:
np.any(filedata > 50, axis=0)
np.all(filedata > 50, axis=0)

NameError: name 'filedata' is not defined

In [188]:
(~((filedata > 50 ) & (filedata < 100))) # or the reverse ~

NameError: name 'filedata' is not defined